version: '3.4'

services:
  rick-and-morty.webapi:
    image: ${DOCKER_REGISTRY-}rickandmortywebapi
    build:
      context: .
      dockerfile: Api/Rick-and-Morty.WebApi/Dockerfile
    ports:
      - "7001:7000"
    #environment:
    #  - ASPNETCORE_ENVIRONMENT=Development
    #  - ASPNETCORE_URLS=https://+:7001
    #  - ASPNETCORE_Kestrel__Certificates__Default__Password=gwG6nkss9ERUYHaU
    #  - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes: 
      - /home/ram_root/:/app/wwwroot
      #- ~/.aspnet/https:/https:ro
